# Generated by Django 4.2.4 on 2023-10-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_updated',
        ),
    ]
